# This is a generated file. Not intended for manual editing.
services:
  webapi666:
    build:
      context: "C:\\Projekty Visual\\PIT38-Tax-Calculator\\TaxEtoro"
      dockerfile: "../WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\marto\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\marto\\.nuget\\packages"
    image: "webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\marto\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Projekty Visual\\PIT38-Tax-Calculator\\WebApi:/app:rw"
    - "C:\\Projekty Visual\\PIT38-Tax-Calculator\\TaxEtoro:/src:rw"
    working_dir: "/app"
