  postgres:
    restart: unless-stopped
    image: postgres:16-alpine
    container_name: postgres
    env_file: postgres.env
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD = password
      - POSTGRES_USER = admin
      - POSTGRES_DB = baza
