services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: ../WebApi/Dockerfile
      
  postgres:
    restart: unless-stopped
    image: postgres:16-alpine
    container_name: postgres
    env_file: postgres.env
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
